In [1]:
# Face filters (Snapchat like) using OpenCV
# @author:- Kunal Gupta (cite as kg777)

import cv2
import sys
import logging as log
import datetime as dt
from time import sleep
import numpy as np
import os
import subprocess

cascPath = "C:\Users\ykim\Downloads\opencv-2.4.10\opencv\sources\data\haarcascades\haarcascade_frontalface_default.xml"  # for face detection

# if not os.path.exists(cascPath):
#     subprocess.call('C:\Users\ykim\Desktop\git\OpenCV-face-filters\download_filters.sh', shell=True)
# else:
#     print('Filters already exist!')

faceCascade = cv2.CascadeClassifier(cascPath)
log.basicConfig(filename='webcam.log',level=log.INFO)

video_capture = cv2.VideoCapture(0)

anterior = 0
mst = cv2.imread('moustache.png')
hat = cv2.imread('cowboy_hat.png')
dog = cv2.imread('dog_filter.png')


def put_moustache(mst,fc,x,y,w,h):
    
    face_width = w
    face_height = h

    mst_width = int(face_width*0.4166666)+1
    mst_height = int(face_height*0.142857)+1



    mst = cv2.resize(mst,(mst_width,mst_height))

    for i in range(int(0.62857142857*face_height),int(0.62857142857*face_height)+mst_height):
        for j in range(int(0.29166666666*face_width),int(0.29166666666*face_width)+mst_width):
            for k in range(3):
                if mst[i-int(0.62857142857*face_height)][j-int(0.29166666666*face_width)][k] <235:
                    fc[y+i][x+j][k] = mst[i-int(0.62857142857*face_height)][j-int(0.29166666666*face_width)][k]
    return fc

def put_hat(hat,fc,x,y,w,h):
    
    face_width = w
    face_height = h
    
    hat_width = face_width+1
    hat_height = int(0.35*face_height)+1
    
    hat = cv2.resize(hat,(hat_width,hat_height))
    
    for i in range(hat_height):
        for j in range(hat_width):
            for k in range(3):
                if hat[i][j][k]<235:
                    fc[y+i-int(0.25*face_height)][x+j][k] = hat[i][j][k]
    return fc

def put_dog_filter(dog,fc,x,y,w,h):
    face_width = w
    face_height = h
    
    dog = cv2.resize(dog,(int(face_width*1.5),int(face_height*1.75)))
    for i in range(int(face_height*1.75)):
        for j in range(int(face_width*1.5)):
            for k in range(3):
                if dog[i][j][k]<235:
                    fc[y+i-int(0.375*h)-1][x+j-int(0.25*w)][k] = dog[i][j][k]
    return fc
    
    
ch = 0
print "Select Filter:1.) Hat 2.) Moustache 3.) Hat and Moustache 4.) Dog Filter"
ch = int(raw_input())
    
    
while True:
    if not video_capture.isOpened():
        print('Unable to load camera.')
        sleep(5)
        pass

    # Capture frame-by-frame
    ret, frame = video_capture.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(40,40)
    )

    # Draw a rectangle around the faces
    for (x, y, w, h) in faces:
        #cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        #cv2.putText(frame,"Person Detected",(x,y),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
        
        if ch==2:
            frame = put_moustache(mst,frame,x,y,w,h)
        elif ch==1:
            frame = put_hat(hat,frame,x,y,w,h)
        elif ch==3:
            frame = put_moustache(mst,frame,x,y,w,h)
            frame = put_hat(hat,frame,x,y,w,h)
        else:
            frame = put_dog_filter(dog,frame,x,y,w,h)
            
            
            
    if anterior != len(faces):
        anterior = len(faces)
        log.info("faces: "+str(len(faces))+" at "+str(dt.datetime.now()))


    # Display the resulting frame
    cv2.imshow('Video', frame)


    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

    

# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()


Select Filter:1.) Hat 2.) Moustache 3.) Hat and Moustache 4.) Dog Filter
1
[[[ 53  55  75]
  [ 46  48  68]
  [ 53  49  67]
  ..., 
  [ 70  94 110]
  [ 73  94 111]
  [ 73  94 111]]

 [[ 50  55  67]
  [ 49  54  66]
  [ 47  50  62]
  ..., 
  [ 76  98 112]
  [ 76  97 109]
  [ 71  92 104]]

 [[ 50  55  65]
  [ 51  56  66]
  [ 46  52  60]
  ..., 
  [ 78 100 114]
  [ 80  99 109]
  [ 73  92 102]]

 ..., 
 [[ 22  32  27]
  [ 24  34  29]
  [ 25  34  34]
  ..., 
  [ 84  67  38]
  [ 84  64  36]
  [ 86  66  38]]

 [[ 22  32  27]
  [ 24  34  29]
  [ 26  34  37]
  ..., 
  [ 85  65  37]
  [ 87  65  37]
  [ 89  67  39]]

 [[ 23  32  30]
  [ 24  33  31]
  [ 24  31  36]
  ..., 
  [ 85  65  37]
  [ 90  68  40]
  [ 94  72  44]]]
[[[ 47  58  65]
  [ 48  59  66]
  [ 42  62  63]
  ..., 
  [ 75  96 108]
  [ 78  99 111]
  [ 78  99 111]]

 [[ 46  58  67]
  [ 45  57  66]
  [ 44  60  66]
  ..., 
  [ 77  95 108]
  [ 80  96 109]
  [ 82  98 111]]

 [[ 47  59  70]
  [ 43  55  66]
  [ 43  58  66]
  ..., 
  [ 80  96 109

[[[ 43  61  67]
  [ 41  59  65]
  [ 40  57  65]
  ..., 
  [ 81 102 105]
  [ 73  95 102]
  [ 74  96 103]]

 [[ 42  60  66]
  [ 40  58  64]
  [ 40  58  64]
  ..., 
  [ 78  98 104]
  [ 81 100 108]
  [ 81 100 108]]

 [[ 42  60  66]
  [ 40  58  64]
  [ 36  53  61]
  ..., 
  [ 74  96 103]
  [ 76  97 109]
  [ 80 101 113]]

 ..., 
 [[ 24  31  30]
  [ 23  30  29]
  [ 20  27  26]
  ..., 
  [ 92  66  50]
  [ 90  66  43]
  [ 92  68  45]]

 [[ 23  30  29]
  [ 20  27  26]
  [ 16  23  21]
  ..., 
  [ 91  64  44]
  [ 90  64  41]
  [ 90  64  41]]

 [[ 23  30  29]
  [ 21  28  27]
  [ 20  27  25]
  ..., 
  [ 89  63  40]
  [ 89  64  39]
  [ 89  64  39]]]
[[[ 46  57  71]
  [ 47  58  72]
  [ 53  57  72]
  ..., 
  [ 84  97 112]
  [ 88  96 112]
  [ 88  96 112]]

 [[ 43  53  69]
  [ 46  56  72]
  [ 52  57  74]
  ..., 
  [ 82  98 111]
  [ 84  95 109]
  [ 83  94 108]]

 [[ 45  53  69]
  [ 47  55  71]
  [ 50  55  72]
  ..., 
  [ 79  95 108]
  [ 80  94 107]
  [ 80  94 107]]

 ..., 
 [[ 25  31  34]
  [ 23  29  32]


[[[ 34  54  55]
  [ 30  50  51]
  [ 36  54  55]
  ..., 
  [ 73  94 111]
  [ 73  93 107]
  [ 76  96 110]]

 [[ 39  56  59]
  [ 36  53  56]
  [ 38  55  58]
  ..., 
  [ 80 101 113]
  [ 81  99 112]
  [ 80  98 111]]

 [[ 41  56  64]
  [ 41  56  64]
  [ 43  56  63]
  ..., 
  [ 81 100 110]
  [ 81 100 110]
  [ 80  99 109]]

 ..., 
 [[ 25  32  31]
  [ 23  30  29]
  [ 23  30  29]
  ..., 
  [ 92  65  45]
  [ 97  67  48]
  [ 98  68  49]]

 [[ 25  32  31]
  [ 24  31  30]
  [ 26  30  30]
  ..., 
  [ 90  65  47]
  [ 89  64  46]
  [ 95  70  52]]

 [[ 27  31  31]
  [ 27  31  31]
  [ 28  32  32]
  ..., 
  [ 90  65  47]
  [ 89  64  46]
  [ 93  68  50]]]
[[[ 39  51  69]
  [ 39  51  69]
  [ 33  51  70]
  ..., 
  [ 72 100  97]
  [ 66 101  97]
  [ 66 101  97]]

 [[ 41  54  69]
  [ 39  52  67]
  [ 35  50  72]
  ..., 
  [ 75  99 101]
  [ 68  99 100]
  [ 67  98  99]]

 [[ 45  55  71]
  [ 43  53  69]
  [ 36  48  73]
  ..., 
  [ 75  97 104]
  [ 73  98 103]
  [ 71  96 101]]

 ..., 
 [[ 21  30  30]
  [ 21  30  30]


[[[ 39  57  58]
  [ 41  59  60]
  [ 44  60  58]
  ..., 
  [ 82  97 105]
  [ 80  99 102]
  [ 80  99 102]]

 [[ 37  54  57]
  [ 41  58  61]
  [ 46  59  61]
  ..., 
  [ 78  94 100]
  [ 77  97 103]
  [ 78  98 104]]

 [[ 39  53  57]
  [ 43  57  61]
  [ 47  60  62]
  ..., 
  [ 76  93 101]
  [ 76  96 102]
  [ 77  97 103]]

 ..., 
 [[ 23  31  26]
  [ 25  33  28]
  [ 27  31  30]
  ..., 
  [ 94  72  44]
  [ 97  74  44]
  [ 97  74  44]]

 [[ 22  26  25]
  [ 26  30  29]
  [ 26  30  29]
  ..., 
  [ 94  71  46]
  [ 96  75  45]
  [ 96  75  45]]

 [[ 23  27  26]
  [ 23  27  26]
  [ 25  29  29]
  ..., 
  [ 91  68  50]
  [ 91  71  43]
  [ 92  72  44]]]
[[[ 32  50  69]
  [ 32  50  69]
  [ 38  55  70]
  ..., 
  [ 84  95 115]
  [ 80  93 115]
  [ 80  93 115]]

 [[ 42  55  75]
  [ 39  52  72]
  [ 36  50  68]
  ..., 
  [ 85  96 116]
  [ 82  95 115]
  [ 82  95 115]]

 [[ 39  52  72]
  [ 35  48  68]
  [ 34  48  66]
  ..., 
  [ 83  96 116]
  [ 83  96 116]
  [ 82  95 115]]

 ..., 
 [[ 24  33  33]
  [ 24  33  33]


[[[ 35  58  70]
  [ 34  57  69]
  [ 34  58  67]
  ..., 
  [ 80 101 104]
  [ 82 101 104]
  [ 82 101 104]]

 [[ 35  56  68]
  [ 36  57  69]
  [ 38  57  67]
  ..., 
  [ 84 102 103]
  [ 82 101 104]
  [ 82 101 104]]

 [[ 37  54  69]
  [ 39  56  71]
  [ 39  57  70]
  ..., 
  [ 86 102 101]
  [ 82 102 103]
  [ 79  99 100]]

 ..., 
 [[ 22  31  30]
  [ 22  31  30]
  [ 22  31  30]
  ..., 
  [ 97  68  46]
  [ 97  71  42]
  [ 96  70  41]]

 [[ 25  32  31]
  [ 25  32  31]
  [ 24  31  31]
  ..., 
  [ 94  65  43]
  [ 98  70  41]
  [ 95  67  38]]

 [[ 26  33  32]
  [ 25  32  31]
  [ 24  30  33]
  ..., 
  [ 96  67  45]
  [ 99  71  42]
  [ 96  68  39]]]
[[[ 44  59  69]
  [ 43  58  68]
  [ 44  59  69]
  ..., 
  [ 74  95 107]
  [ 74  97 109]
  [ 74  97 109]]

 [[ 42  59  69]
  [ 42  59  69]
  [ 44  59  69]
  ..., 
  [ 74  95 107]
  [ 73  96 108]
  [ 73  96 108]]

 [[ 42  59  67]
  [ 42  59  67]
  [ 44  59  69]
  ..., 
  [ 74  95 107]
  [ 72  95 107]
  [ 72  95 107]]

 ..., 
 [[ 29  33  33]
  [ 28  32  32]


[[[ 39  56  71]
  [ 42  59  74]
  [ 39  58  75]
  ..., 
  [ 88  95 105]
  [ 90  93 110]
  [ 90  93 110]]

 [[ 38  54  72]
  [ 42  58  76]
  [ 38  56  75]
  ..., 
  [ 90 102 106]
  [ 92  97 109]
  [ 90  95 107]]

 [[ 42  56  74]
  [ 43  57  75]
  [ 40  56  74]
  ..., 
  [ 86  98 102]
  [ 90  95 105]
  [ 92  97 107]]

 ..., 
 [[ 26  30  31]
  [ 27  31  32]
  [ 27  31  32]
  ..., 
  [ 97  71  48]
  [ 98  72  49]
  [ 97  71  48]]

 [[ 25  29  30]
  [ 27  31  32]
  [ 27  31  32]
  ..., 
  [ 95  68  48]
  [ 95  69  46]
  [ 95  69  46]]

 [[ 23  30  30]
  [ 25  32  32]
  [ 25  32  32]
  ..., 
  [ 94  67  47]
  [ 92  68  45]
  [ 92  68  45]]]
[[[ 35  53  66]
  [ 33  51  64]
  [ 43  53  69]
  ..., 
  [ 79  98  95]
  [ 81 100  98]
  [ 82 101  99]]

 [[ 39  54  69]
  [ 36  51  66]
  [ 42  55  70]
  ..., 
  [ 80  99  97]
  [ 80  98  99]
  [ 81  99 100]]

 [[ 42  54  72]
  [ 42  54  72]
  [ 44  57  72]
  ..., 
  [ 82  99 102]
  [ 82  99 102]
  [ 82  99 102]]

 ..., 
 [[ 26  33  33]
  [ 27  34  34]


[[[ 45  64  61]
  [ 45  64  61]
  [ 45  62  65]
  ..., 
  [ 78  97 107]
  [ 84  96 107]
  [ 84  96 107]]

 [[ 45  64  62]
  [ 45  64  62]
  [ 46  64  65]
  ..., 
  [ 78  97 107]
  [ 83  95 106]
  [ 84  96 107]]

 [[ 43  60  63]
  [ 45  62  65]
  [ 45  62  65]
  ..., 
  [ 77  96 106]
  [ 82  94 105]
  [ 83  95 106]]

 ..., 
 [[ 29  33  34]
  [ 27  31  32]
  [ 25  29  29]
  ..., 
  [ 94  67  47]
  [ 97  67  48]
  [ 99  69  50]]

 [[ 28  32  33]
  [ 26  30  31]
  [ 25  29  29]
  ..., 
  [ 96  68  52]
  [ 95  68  48]
  [ 95  68  48]]

 [[ 27  30  34]
  [ 26  29  33]
  [ 25  29  30]
  ..., 
  [ 95  69  53]
  [ 96  69  49]
  [ 95  68  48]]]
[[[ 42  54  72]
  [ 42  54  72]
  [ 44  53  72]
  ..., 
  [ 77  96 106]
  [ 78  97 105]
  [ 80  99 107]]

 [[ 43  55  73]
  [ 42  54  72]
  [ 43  52  71]
  ..., 
  [ 76  95 105]
  [ 78  97 107]
  [ 80  99 109]]

 [[ 46  58  76]
  [ 43  55  73]
  [ 45  52  71]
  ..., 
  [ 77  96 106]
  [ 78  97 107]
  [ 78  97 107]]

 ..., 
 [[ 24  31  36]
  [ 23  30  35]


[[[ 52  57  74]
  [ 51  56  73]
  [ 51  54  71]
  ..., 
  [ 82  97 107]
  [ 78  97 107]
  [ 78  97 107]]

 [[ 54  59  76]
  [ 51  56  73]
  [ 50  52  72]
  ..., 
  [ 84  99 109]
  [ 83 100 110]
  [ 80  97 107]]

 [[ 51  61  77]
  [ 50  60  76]
  [ 49  53  73]
  ..., 
  [ 83 100 110]
  [ 80  98 111]
  [ 78  96 109]]

 ..., 
 [[ 21  32  31]
  [ 19  30  29]
  [ 21  30  29]
  ..., 
  [ 89  69  50]
  [ 90  68  45]
  [ 88  66  43]]

 [[ 21  32  31]
  [ 20  31  30]
  [ 20  31  30]
  ..., 
  [ 89  68  51]
  [ 88  69  45]
  [ 84  65  41]]

 [[ 21  32  31]
  [ 21  32  31]
  [ 21  32  31]
  ..., 
  [ 89  68  51]
  [ 88  68  47]
  [ 85  65  44]]]
[[[ 37  56  64]
  [ 37  56  64]
  [ 37  56  64]
  ..., 
  [ 78  99 111]
  [ 72  98 109]
  [ 78 104 115]]

 [[ 37  55  61]
  [ 39  57  63]
  [ 40  57  65]
  ..., 
  [ 78 100 109]
  [ 70  97 105]
  [ 75 102 110]]

 [[ 39  57  63]
  [ 40  58  64]
  [ 41  59  65]
  ..., 
  [ 76  94 107]
  [ 74  98 107]
  [ 74  98 107]]

 ..., 
 [[ 26  33  33]
  [ 27  34  34]


[[[ 47  53  68]
  [ 43  49  64]
  [ 45  51  66]
  ..., 
  [ 70  97 103]
  [ 77  96 106]
  [ 77  96 106]]

 [[ 42  48  63]
  [ 43  49  64]
  [ 45  52  64]
  ..., 
  [ 70  98 102]
  [ 77  96 106]
  [ 78  97 107]]

 [[ 41  51  62]
  [ 43  53  64]
  [ 48  55  65]
  ..., 
  [ 70  98 102]
  [ 77  96 106]
  [ 78  97 107]]

 ..., 
 [[ 26  33  33]
  [ 26  33  33]
  [ 25  32  32]
  ..., 
  [ 86  62  46]
  [ 94  69  51]
  [100  75  57]]

 [[ 24  31  31]
  [ 25  32  32]
  [ 25  32  32]
  ..., 
  [ 92  67  54]
  [ 95  70  52]
  [ 96  71  53]]

 [[ 22  30  33]
  [ 23  31  34]
  [ 23  31  34]
  ..., 
  [ 93  69  53]
  [ 93  68  50]
  [ 93  68  50]]]
[[[ 42  60  66]
  [ 41  59  65]
  [ 39  60  63]
  ..., 
  [ 72  98 114]
  [ 75  94 111]
  [ 75  94 111]]

 [[ 42  58  64]
  [ 43  59  65]
  [ 41  60  63]
  ..., 
  [ 78  98 112]
  [ 77  94 109]
  [ 78  95 110]]

 [[ 41  57  63]
  [ 43  59  65]
  [ 41  59  65]
  ..., 
  [ 78  96 109]
  [ 80  96 109]
  [ 78  94 107]]

 ..., 
 [[ 25  33  28]
  [ 26  34  29]


[[[ 41  56  66]
  [ 38  53  63]
  [ 37  54  57]
  ..., 
  [ 73  95 102]
  [ 75  97  98]
  [ 75  97  98]]

 [[ 41  55  68]
  [ 41  55  68]
  [ 41  56  64]
  ..., 
  [ 74  96 105]
  [ 74  98 100]
  [ 74  98 100]]

 [[ 43  54  68]
  [ 44  55  69]
  [ 43  58  68]
  ..., 
  [ 76  98 107]
  [ 76  99 104]
  [ 75  98 103]]

 ..., 
 [[ 30  32  38]
  [ 33  35  41]
  [ 36  36  42]
  ..., 
  [ 87  61  45]
  [ 87  57  38]
  [ 91  61  42]]

 [[ 35  35  41]
  [ 37  37  43]
  [ 47  42  46]
  ..., 
  [ 88  61  48]
  [ 88  60  44]
  [ 89  61  45]]

 [[ 49  41  46]
  [ 46  38  43]
  [ 59  43  45]
  ..., 
  [ 89  61  50]
  [ 89  61  50]
  [ 89  61  50]]]
[[[ 47  52  69]
  [ 49  54  71]
  [ 49  54  71]
  ..., 
  [ 74  96 103]
  [ 77  94 102]
  [ 78  95 103]]

 [[ 45  53  69]
  [ 48  56  72]
  [ 48  57  71]
  ..., 
  [ 75  97 104]
  [ 75  97 104]
  [ 75  97 104]]

 [[ 46  54  70]
  [ 48  56  72]
  [ 48  57  71]
  ..., 
  [ 75  97 106]
  [ 76  98 105]
  [ 75  97 104]]

 ..., 
 [[ 33  33  34]
  [ 34  34  35]


[[[ 42  57  72]
  [ 41  56  71]
  [ 36  52  65]
  ..., 
  [ 84  94 110]
  [ 86  94 110]
  [ 86  94 110]]

 [[ 46  62  75]
  [ 43  59  72]
  [ 39  55  68]
  ..., 
  [ 82  98 111]
  [ 84  94 110]
  [ 83  93 109]]

 [[ 42  59  69]
  [ 43  60  70]
  [ 41  58  68]
  ..., 
  [ 81  99 112]
  [ 84  94 110]
  [ 83  93 109]]

 ..., 
 [[ 23  33  36]
  [ 23  33  36]
  [ 24  34  37]
  ..., 
  [ 84  64  43]
  [ 87  64  39]
  [ 93  70  45]]

 [[ 22  32  35]
  [ 22  32  35]
  [ 22  32  35]
  ..., 
  [ 84  66  47]
  [ 88  65  40]
  [ 89  66  41]]

 [[ 24  32  35]
  [ 24  32  35]
  [ 22  32  35]
  ..., 
  [ 82  67  47]
  [ 87  65  42]
  [ 87  65  42]]]
[[[ 46  59  79]
  [ 44  57  77]
  [ 44  56  81]
  ..., 
  [ 86  95 114]
  [ 82  97 107]
  [ 82  97 107]]

 [[ 44  58  76]
  [ 43  57  75]
  [ 44  57  77]
  ..., 
  [ 84  98 111]
  [ 80  97 107]
  [ 80  97 107]]

 [[ 45  57  75]
  [ 44  56  74]
  [ 45  56  76]
  ..., 
  [ 80  96 109]
  [ 79  96 106]
  [ 79  96 106]]

 ..., 
 [[ 27  34  34]
  [ 25  32  32]


[[[ 47  54  80]
  [ 47  54  80]
  [ 44  54  79]
  ..., 
  [ 79  96 106]
  [ 86  96 107]
  [ 88  98 109]]

 [[ 48  55  81]
  [ 47  54  80]
  [ 46  53  79]
  ..., 
  [ 75  93 106]
  [ 82  97 107]
  [ 84  99 109]]

 [[ 47  54  80]
  [ 47  54  80]
  [ 46  53  79]
  ..., 
  [ 78  96 109]
  [ 82  99 109]
  [ 80  97 107]]

 ..., 
 [[ 21  32  32]
  [ 21  32  32]
  [ 19  30  30]
  ..., 
  [ 94  68  45]
  [ 98  72  43]
  [ 99  73  44]]

 [[ 21  32  32]
  [ 23  34  34]
  [ 21  32  32]
  ..., 
  [ 95  68  48]
  [ 97  70  43]
  [ 94  67  40]]

 [[ 23  32  32]
  [ 25  34  34]
  [ 25  34  34]
  ..., 
  [ 95  68  50]
  [ 96  69  42]
  [ 93  66  39]]]
[[[ 52  55  72]
  [ 52  55  72]
  [ 51  54  71]
  ..., 
  [ 69  90 107]
  [ 76  91 111]
  [ 82  97 117]]

 [[ 48  55  74]
  [ 47  54  73]
  [ 49  54  71]
  ..., 
  [ 71  93 107]
  [ 75  94 111]
  [ 78  97 114]]

 [[ 46  55  74]
  [ 44  53  72]
  [ 46  53  72]
  ..., 
  [ 71  97 108]
  [ 76  93 108]
  [ 74  91 106]]

 ..., 
 [[ 23  33  36]
  [ 24  34  37]


[[[ 37  59  68]
  [ 36  58  67]
  [ 43  55  66]
  ..., 
  [ 73  93 107]
  [ 82 101 109]
  [ 85 104 112]]

 [[ 38  60  69]
  [ 37  59  68]
  [ 42  56  69]
  ..., 
  [ 75  95 109]
  [ 79 101 110]
  [ 81 103 112]]

 [[ 40  58  71]
  [ 39  57  70]
  [ 43  57  70]
  ..., 
  [ 78  98 112]
  [ 72  92 106]
  [ 68  88 102]]

 ..., 
 [[ 26  30  31]
  [ 29  33  34]
  [ 30  37  37]
  ..., 
  [ 90  67  37]
  [ 94  69  35]
  [ 94  69  35]]

 [[ 28  32  33]
  [ 29  33  34]
  [ 32  36  37]
  ..., 
  [ 88  67  37]
  [ 89  66  36]
  [ 88  65  35]]

 [[ 28  32  33]
  [ 29  33  34]
  [ 29  33  34]
  ..., 
  [ 86  67  37]
  [ 88  67  37]
  [ 88  67  37]]]
[[[ 49  55  76]
  [ 49  55  76]
  [ 39  50  70]
  ..., 
  [ 74  96 103]
  [ 81  97 103]
  [ 81  97 103]]

 [[ 48  58  74]
  [ 50  60  76]
  [ 43  56  71]
  ..., 
  [ 77  96 104]
  [ 84  99 107]
  [ 85 100 108]]

 [[ 48  59  73]
  [ 47  58  72]
  [ 42  56  69]
  ..., 
  [ 80  99 107]
  [ 84 101 109]
  [ 83 100 108]]

 ..., 
 [[ 26  30  31]
  [ 27  31  32]


[[[ 41  56  78]
  [ 40  55  77]
  [ 40  55  77]
  ..., 
  [ 72  95 113]
  [ 79  94 109]
  [ 78  93 108]]

 [[ 43  56  76]
  [ 42  55  75]
  [ 41  55  73]
  ..., 
  [ 73  93 112]
  [ 78  93 108]
  [ 78  93 108]]

 [[ 47  57  73]
  [ 46  56  72]
  [ 43  56  71]
  ..., 
  [ 75  93 112]
  [ 78  93 108]
  [ 75  90 105]]

 ..., 
 [[ 24  31  31]
  [ 25  32  32]
  [ 24  30  33]
  ..., 
  [ 95  59  45]
  [ 97  67  50]
  [ 98  68  51]]

 [[ 26  33  33]
  [ 25  32  32]
  [ 24  30  33]
  ..., 
  [ 94  61  46]
  [100  70  53]
  [ 99  69  52]]

 [[ 26  33  33]
  [ 25  32  32]
  [ 24  30  33]
  ..., 
  [ 94  60  48]
  [ 96  66  49]
  [100  70  53]]]
[[[ 42  58  64]
  [ 41  57  63]
  [ 39  58  56]
  ..., 
  [ 78  96 117]
  [ 78  92 117]
  [ 76  90 115]]

 [[ 45  59  63]
  [ 45  59  63]
  [ 43  58  60]
  ..., 
  [ 78  96 115]
  [ 72  90 109]
  [ 73  91 110]]

 [[ 45  59  63]
  [ 45  59  63]
  [ 46  61  63]
  ..., 
  [ 73  92 109]
  [ 74  93 110]
  [ 74  93 110]]

 ..., 
 [[ 27  31  30]
  [ 26  30  29]


[[[ 56  63  68]
  [ 57  64  69]
  [ 49  59  62]
  ..., 
  [ 84  99 109]
  [ 86  98 109]
  [ 86  98 109]]

 [[ 51  60  65]
  [ 54  63  68]
  [ 47  59  63]
  ..., 
  [ 82  96 109]
  [ 84  95 109]
  [ 84  95 109]]

 [[ 50  59  64]
  [ 50  59  64]
  [ 47  58  65]
  ..., 
  [ 82  95 110]
  [ 84  94 110]
  [ 84  94 110]]

 ..., 
 [[ 22  30  33]
  [ 19  27  30]
  [ 23  31  34]
  ..., 
  [ 90  65  45]
  [ 96  71  46]
  [ 95  70  45]]

 [[ 22  31  31]
  [ 22  31  31]
  [ 24  33  33]
  ..., 
  [ 93  68  50]
  [ 92  68  45]
  [ 92  68  45]]

 [[ 22  31  31]
  [ 22  31  31]
  [ 24  33  33]
  ..., 
  [ 92  66  50]
  [ 92  67  47]
  [ 90  65  45]]]
[[[ 43  60  70]
  [ 41  58  68]
  [ 38  57  65]
  ..., 
  [ 84  95 109]
  [ 85  99 112]
  [ 85  99 112]]

 [[ 41  58  68]
  [ 40  57  67]
  [ 39  56  64]
  ..., 
  [ 81  94 109]
  [ 80  95 110]
  [ 82  97 112]]

 [[ 43  58  68]
  [ 41  56  66]
  [ 39  54  62]
  ..., 
  [ 79  92 107]
  [ 78  93 108]
  [ 79  94 109]]

 ..., 
 [[ 21  32  32]
  [ 20  31  31]


[[[ 59  69  78]
  [ 60  70  79]
  [ 63  70  82]
  ..., 
  [ 91 107 120]
  [ 90 111 123]
  [ 89 110 122]]

 [[ 56  67  74]
  [ 57  68  75]
  [ 62  69  79]
  ..., 
  [ 96 111 121]
  [ 92 111 121]
  [ 90 109 119]]

 [[ 55  67  71]
  [ 56  68  72]
  [ 64  71  81]
  ..., 
  [ 96 111 121]
  [ 92 111 121]
  [ 88 107 117]]

 ..., 
 [[ 32  39  37]
  [ 30  37  35]
  [ 32  36  35]
  ..., 
  [108  80  42]
  [111  84  52]
  [115  88  56]]

 [[ 28  35  34]
  [ 27  34  33]
  [ 27  34  33]
  ..., 
  [110  80  47]
  [108  79  57]
  [109  80  58]]

 [[ 28  35  34]
  [ 26  33  32]
  [ 26  33  32]
  ..., 
  [102  74  45]
  [105  75  58]
  [112  82  65]]]
[[[ 61  66  71]
  [ 61  66  71]
  [ 63  67  82]
  ..., 
  [ 99 115 128]
  [101 115 128]
  [ 99 113 126]]

 [[ 58  64  72]
  [ 60  66  74]
  [ 61  67  82]
  ..., 
  [101 113 124]
  [103 113 124]
  [100 110 121]]

 [[ 57  64  76]
  [ 58  65  77]
  [ 59  65  80]
  ..., 
  [100 110 119]
  [100 107 117]
  [ 97 104 114]]

 ..., 
 [[ 31  38  37]
  [ 32  39  38]


[[[ 52  70  71]
  [ 51  69  70]
  [ 51  67  65]
  ..., 
  [ 96 114 127]
  [ 99 113 131]
  [ 94 108 126]]

 [[ 53  66  73]
  [ 54  67  74]
  [ 54  68  72]
  ..., 
  [ 96 113 123]
  [101 115 128]
  [ 98 112 125]]

 [[ 52  64  75]
  [ 50  62  73]
  [ 55  65  74]
  ..., 
  [ 93 110 120]
  [ 95 110 120]
  [ 98 113 123]]

 ..., 
 [[ 34  36  35]
  [ 34  36  35]
  [ 34  36  35]
  ..., 
  [101  80  43]
  [107  83  42]
  [106  82  41]]

 [[ 32  36  36]
  [ 30  34  34]
  [ 32  36  36]
  ..., 
  [103  81  46]
  [106  81  42]
  [106  81  42]]

 [[ 31  38  37]
  [ 27  34  33]
  [ 27  34  33]
  ..., 
  [103  81  48]
  [106  81  42]
  [105  80  41]]]
[[[ 57  73  86]
  [ 56  72  85]
  [ 51  66  81]
  ..., 
  [ 98 112 116]
  [101 116 118]
  [101 116 118]]

 [[ 57  73  86]
  [ 57  73  86]
  [ 55  71  84]
  ..., 
  [100 112 116]
  [102 116 115]
  [103 117 116]]

 [[ 58  72  85]
  [ 58  72  85]
  [ 57  71  84]
  ..., 
  [ 99 111 115]
  [102 116 115]
  [102 116 115]]

 ..., 
 [[ 34  36  35]
  [ 35  37  36]


[[[ 30  46  52]
  [ 30  46  52]
  [ 29  46  49]
  ..., 
  [ 61  82  94]
  [ 64  80  98]
  [ 64  80  98]]

 [[ 32  44  53]
  [ 32  44  53]
  [ 31  44  51]
  ..., 
  [ 62  82  96]
  [ 64  84  98]
  [ 64  84  98]]

 [[ 33  43  52]
  [ 34  44  53]
  [ 32  45  52]
  ..., 
  [ 62  82  96]
  [ 64  84  98]
  [ 66  86 100]]

 ..., 
 [[ 20  26  29]
  [ 19  25  28]
  [ 20  26  29]
  ..., 
  [ 78  56  33]
  [ 77  54  34]
  [ 77  54  34]]

 [[ 18  24  27]
  [ 17  23  26]
  [ 14  21  21]
  ..., 
  [ 74  54  33]
  [ 77  54  34]
  [ 77  54  34]]

 [[ 16  22  25]
  [ 14  20  23]
  [ 16  20  21]
  ..., 
  [ 76  56  37]
  [ 81  58  38]
  [ 80  57  37]]]
[[[ 39  54  64]
  [ 41  56  66]
  [ 39  52  67]
  ..., 
  [ 70  86 104]
  [ 72  86 104]
  [ 72  86 104]]

 [[ 38  53  63]
  [ 38  53  63]
  [ 39  49  65]
  ..., 
  [ 76  94 107]
  [ 73  90 105]
  [ 71  88 103]]

 [[ 40  52  63]
  [ 40  52  63]
  [ 41  49  65]
  ..., 
  [ 79  95 108]
  [ 73  91 104]
  [ 73  91 104]]

 ..., 
 [[ 17  31  29]
  [ 14  28  26]


[[[30 41 40]
  [33 44 43]
  [36 45 45]
  ..., 
  [63 78 93]
  [63 77 95]
  [63 77 95]]

 [[31 42 41]
  [33 44 43]
  [36 45 45]
  ..., 
  [65 81 94]
  [64 80 93]
  [64 80 93]]

 [[30 41 41]
  [34 45 45]
  [36 45 45]
  ..., 
  [66 82 95]
  [65 81 94]
  [64 80 93]]

 ..., 
 [[17 26 26]
  [18 27 27]
  [16 25 25]
  ..., 
  [72 52 33]
  [75 55 36]
  [76 56 37]]

 [[16 27 27]
  [15 26 26]
  [15 26 26]
  ..., 
  [72 51 34]
  [74 52 38]
  [75 53 39]]

 [[14 25 25]
  [14 25 25]
  [14 25 25]
  ..., 
  [71 49 35]
  [72 50 36]
  [74 52 38]]]
[[[31 45 49]
  [30 44 48]
  [30 44 48]
  ..., 
  [65 81 87]
  [68 82 95]
  [67 81 94]]

 [[32 46 50]
  [31 45 49]
  [30 44 48]
  ..., 
  [65 80 88]
  [71 80 94]
  [70 79 93]]

 [[32 45 52]
  [31 44 51]
  [30 43 50]
  ..., 
  [65 77 86]
  [68 76 92]
  [68 76 92]]

 ..., 
 [[21 26 31]
  [19 24 29]
  [16 20 28]
  ..., 
  [74 50 34]
  [77 54 34]
  [77 54 34]]

 [[17 24 29]
  [17 24 29]
  [16 21 26]
  ..., 
  [74 52 38]
  [77 54 34]
  [77 54 34]]

 [[16 23 28]
  [17

[[[32 48 54]
  [32 48 54]
  [34 46 57]
  ..., 
  [53 78 83]
  [63 82 90]
  [63 82 90]]

 [[29 46 49]
  [30 47 50]
  [31 46 56]
  ..., 
  [52 74 83]
  [57 76 86]
  [59 78 88]]

 [[28 45 48]
  [28 45 48]
  [29 45 51]
  ..., 
  [57 78 90]
  [61 80 90]
  [61 80 90]]

 ..., 
 [[23 27 27]
  [22 26 26]
  [21 25 26]
  ..., 
  [74 52 29]
  [78 55 30]
  [79 56 31]]

 [[21 28 28]
  [21 28 28]
  [21 28 28]
  ..., 
  [71 51 32]
  [75 51 28]
  [76 52 29]]

 [[18 27 27]
  [19 28 28]
  [19 28 28]
  ..., 
  [71 49 35]
  [73 50 32]
  [73 50 32]]]
[[[35 43 51]
  [36 44 52]
  [34 44 53]
  ..., 
  [48 75 88]
  [46 76 87]
  [46 76 87]]

 [[34 42 50]
  [37 45 53]
  [37 44 56]
  ..., 
  [51 76 89]
  [45 74 87]
  [43 72 85]]

 [[34 41 51]
  [35 42 52]
  [34 40 55]
  ..., 
  [53 77 93]
  [47 75 91]
  [45 73 89]]

 ..., 
 [[25 28 32]
  [23 26 30]
  [23 26 30]
  ..., 
  [74 56 35]
  [76 58 37]
  [75 57 36]]

 [[20 22 28]
  [22 24 30]
  [22 25 29]
  ..., 
  [75 57 38]
  [75 57 36]
  [74 56 35]]

 [[22 21 30]
  [23

[[[ 43  59  72]
  [ 44  60  73]
  [ 45  60  70]
  ..., 
  [ 96 105 105]
  [ 94 103 103]
  [100 109 109]]

 [[ 49  63  76]
  [ 46  60  73]
  [ 46  61  71]
  ..., 
  [ 95 106 106]
  [ 97 108 107]
  [ 99 110 109]]

 [[ 49  64  74]
  [ 43  58  68]
  [ 44  59  69]
  ..., 
  [ 97 108 108]
  [ 97 108 107]
  [ 98 109 108]]

 ..., 
 [[ 29  34  30]
  [ 29  34  30]
  [ 29  34  30]
  ..., 
  [ 99  72  40]
  [101  75  46]
  [105  79  50]]

 [[ 29  33  32]
  [ 28  32  31]
  [ 30  34  33]
  ..., 
  [100  70  46]
  [103  75  51]
  [104  76  52]]

 [[ 27  34  32]
  [ 26  33  31]
  [ 27  34  32]
  ..., 
  [ 98  71  51]
  [102  76  53]
  [101  75  52]]]
[[[ 53  63  74]
  [ 54  64  75]
  [ 56  64  72]
  ..., 
  [ 93 100 110]
  [ 89 104 106]
  [ 89 104 106]]

 [[ 54  64  75]
  [ 54  64  75]
  [ 54  64  73]
  ..., 
  [ 94 103 108]
  [ 91 104 106]
  [ 91 104 106]]

 [[ 56  66  77]
  [ 55  65  76]
  [ 50  60  71]
  ..., 
  [ 93 104 104]
  [ 90 104 103]
  [ 91 105 104]]

 ..., 
 [[ 36  39  30]
  [ 36  39  30]


[[[ 48  66  67]
  [ 49  67  68]
  [ 48  67  70]
  ..., 
  [ 88 105 108]
  [ 90 101 101]
  [ 91 102 102]]

 [[ 54  66  75]
  [ 53  65  74]
  [ 50  65  75]
  ..., 
  [ 88 105 108]
  [ 92 102 105]
  [ 92 102 105]]

 [[ 59  69  85]
  [ 54  64  80]
  [ 51  65  78]
  ..., 
  [ 90 109 112]
  [ 92 104 108]
  [ 91 103 107]]

 ..., 
 [[ 34  36  35]
  [ 32  34  33]
  [ 32  34  34]
  ..., 
  [101  79  44]
  [103  79  43]
  [106  82  46]]

 [[ 34  36  35]
  [ 32  34  33]
  [ 31  33  33]
  ..., 
  [ 97  74  35]
  [ 98  74  38]
  [100  76  40]]

 [[ 32  36  36]
  [ 32  36  36]
  [ 28  32  32]
  ..., 
  [ 94  73  29]
  [ 97  74  35]
  [ 99  76  37]]]
[[[ 52  64  75]
  [ 53  65  76]
  [ 55  66  73]
  ..., 
  [ 92 106 105]
  [ 87 106 104]
  [ 89 108 106]]

 [[ 53  68  78]
  [ 51  66  76]
  [ 53  65  74]
  ..., 
  [ 95 109 108]
  [ 96 112 111]
  [ 95 111 110]]

 [[ 50  67  75]
  [ 49  66  74]
  [ 49  65  71]
  ..., 
  [ 91 105 104]
  [ 87 106 103]
  [ 91 110 107]]

 ..., 
 [[ 27  38  38]
  [ 26  37  37]


[[[ 47  55  71]
  [ 47  55  71]
  [ 45  50  67]
  ..., 
  [ 74  96 105]
  [ 73  97 104]
  [ 72  96 103]]

 [[ 47  52  69]
  [ 47  52  69]
  [ 45  49  69]
  ..., 
  [ 73  95 104]
  [ 74  96 105]
  [ 73  95 104]]

 [[ 45  49  69]
  [ 43  47  67]
  [ 46  48  68]
  ..., 
  [ 70  94 103]
  [ 71  95 104]
  [ 70  94 103]]

 ..., 
 [[ 23  30  30]
  [ 18  25  25]
  [ 23  30  30]
  ..., 
  [ 92  64  40]
  [ 89  66  36]
  [ 90  67  37]]

 [[ 27  31  32]
  [ 23  27  28]
  [ 26  30  31]
  ..., 
  [ 91  63  39]
  [ 89  65  37]
  [ 90  66  38]]

 [[ 29  31  32]
  [ 31  33  34]
  [ 29  33  34]
  ..., 
  [ 90  64  41]
  [ 91  67  39]
  [ 91  67  39]]]
[[[ 44  54  70]
  [ 44  54  70]
  [ 42  55  70]
  ..., 
  [ 83 101 107]
  [ 76 100 109]
  [ 72  96 105]]

 [[ 41  53  64]
  [ 43  55  66]
  [ 45  57  68]
  ..., 
  [ 82  99 107]
  [ 71  95 104]
  [ 71  95 104]]

 [[ 40  52  63]
  [ 44  56  67]
  [ 45  57  68]
  ..., 
  [ 80  97 105]
  [ 72  94 103]
  [ 73  95 104]]

 ..., 
 [[ 24  34  29]
  [ 24  34  29]


[[[ 31  50  58]
  [ 31  50  58]
  [ 32  55  53]
  ..., 
  [ 76  93 108]
  [ 75  92 107]
  [ 75  92 107]]

 [[ 34  49  57]
  [ 36  51  59]
  [ 37  55  56]
  ..., 
  [ 75  91 109]
  [ 74  91 106]
  [ 76  93 108]]

 [[ 39  51  60]
  [ 39  51  60]
  [ 40  55  57]
  ..., 
  [ 76  93 108]
  [ 78  93 108]
  [ 78  93 108]]

 ..., 
 [[ 23  30  28]
  [ 25  32  30]
  [ 25  32  31]
  ..., 
  [ 92  65  33]
  [ 96  63  35]
  [103  70  42]]

 [[ 23  30  30]
  [ 25  32  32]
  [ 26  32  35]
  ..., 
  [ 93  68  36]
  [ 98  68  37]
  [103  73  42]]

 [[ 23  29  32]
  [ 24  30  33]
  [ 26  31  36]
  ..., 
  [ 91  68  38]
  [ 96  69  37]
  [100  73  41]]]
[[[ 48  52  72]
  [ 45  49  69]
  [ 28  50  64]
  ..., 
  [ 74  96 103]
  [ 75  97 104]
  [ 74  96 103]]

 [[ 49  52  69]
  [ 47  50  67]
  [ 35  50  65]
  ..., 
  [ 73  95 104]
  [ 74  96 105]
  [ 73  95 104]]

 [[ 49  53  68]
  [ 47  51  66]
  [ 42  51  65]
  ..., 
  [ 72  94 103]
  [ 73  95 104]
  [ 72  94 103]]

 ..., 
 [[ 22  32  35]
  [ 22  32  35]


[[[ 50  58  61]
  [ 50  58  61]
  [ 52  58  61]
  ..., 
  [ 71  98 104]
  [ 68  95 101]
  [ 67  94 100]]

 [[ 51  59  62]
  [ 49  57  60]
  [ 48  53  58]
  ..., 
  [ 70  97 103]
  [ 68  95 101]
  [ 68  95 101]]

 [[ 55  65  68]
  [ 47  57  60]
  [ 47  54  59]
  ..., 
  [ 70  94 103]
  [ 69  93 100]
  [ 70  94 101]]

 ..., 
 [[ 20  31  29]
  [ 20  31  29]
  [ 22  31  29]
  ..., 
  [ 88  65  45]
  [ 83  67  41]
  [ 84  68  42]]

 [[ 19  30  29]
  [ 19  30  29]
  [ 17  28  26]
  ..., 
  [ 89  68  51]
  [ 86  68  47]
  [ 83  65  44]]

 [[ 16  27  26]
  [ 15  26  25]
  [ 15  26  25]
  ..., 
  [ 89  68  56]
  [ 84  68  50]
  [ 82  66  48]]]
[[[ 44  53  72]
  [ 47  56  75]
  [ 45  55  71]
  ..., 
  [ 80  94 107]
  [ 76  93 108]
  [ 77  94 109]]

 [[ 50  58  74]
  [ 50  58  74]
  [ 48  58  69]
  ..., 
  [ 77  95 108]
  [ 76  97 109]
  [ 75  96 108]]

 [[ 50  56  71]
  [ 50  56  71]
  [ 48  55  65]
  ..., 
  [ 79 100 112]
  [ 79 100 112]
  [ 76  97 109]]

 ..., 
 [[ 22  31  30]
  [ 21  30  29]


[[[ 45  56  70]
  [ 45  56  70]
  [ 46  56  67]
  ..., 
  [ 76  93 103]
  [ 80  92 103]
  [ 81  93 104]]

 [[ 40  51  65]
  [ 41  52  66]
  [ 45  55  66]
  ..., 
  [ 76  93 103]
  [ 81  93 104]
  [ 82  94 105]]

 [[ 40  50  61]
  [ 40  50  61]
  [ 44  51  63]
  ..., 
  [ 78  95 105]
  [ 80  94 107]
  [ 80  94 107]]

 ..., 
 [[ 27  31  32]
  [ 27  31  32]
  [ 27  31  32]
  ..., 
  [ 94  64  40]
  [ 95  65  41]
  [ 96  66  42]]

 [[ 25  32  32]
  [ 26  33  33]
  [ 27  34  34]
  ..., 
  [ 92  65  38]
  [ 93  66  39]
  [ 94  67  40]]

 [[ 24  31  31]
  [ 24  31  31]
  [ 25  32  32]
  ..., 
  [ 90  66  38]
  [ 91  67  39]
  [ 94  70  42]]]
[[[ 59  66  66]
  [ 59  66  66]
  [ 61  65  66]
  ..., 
  [ 99 102 106]
  [ 97 102 107]
  [ 99 104 109]]

 [[ 62  67  72]
  [ 62  67  72]
  [ 60  64  72]
  ..., 
  [ 97 103 106]
  [101 107 110]
  [103 109 112]]

 [[ 60  65  75]
  [ 60  65  75]
  [ 59  64  74]
  ..., 
  [ 95 102 107]
  [100 107 112]
  [101 108 113]]

 ..., 
 [[ 27  34  32]
  [ 27  34  32]


[[[ 51  66  54]
  [ 50  65  53]
  [ 50  66  49]
  ..., 
  [ 84 105 102]
  [ 84 107 103]
  [ 87 110 106]]

 [[ 49  61  56]
  [ 50  62  57]
  [ 48  66  53]
  ..., 
  [ 91 111 104]
  [ 85 108 104]
  [ 87 110 106]]

 [[ 53  62  61]
  [ 53  62  61]
  [ 52  68  60]
  ..., 
  [ 93 111 103]
  [ 89 111 104]
  [ 89 111 104]]

 ..., 
 [[ 35  41  30]
  [ 31  37  26]
  [ 31  36  27]
  ..., 
  [114  84  33]
  [116  86  35]
  [117  87  36]]

 [[ 32  39  30]
  [ 29  36  27]
  [ 28  35  26]
  ..., 
  [114  83  34]
  [115  85  34]
  [115  85  34]]

 [[ 30  37  28]
  [ 29  36  27]
  [ 28  35  26]
  ..., 
  [114  83  34]
  [114  84  33]
  [113  83  32]]]
[[[ 51  60  60]
  [ 50  59  59]
  [ 51  58  57]
  ..., 
  [ 74 102  99]
  [ 78 106 103]
  [ 76 104 101]]

 [[ 49  57  60]
  [ 47  55  58]
  [ 47  55  58]
  ..., 
  [ 74 102  99]
  [ 76 104 101]
  [ 76 104 101]]

 [[ 49  55  63]
  [ 49  55  63]
  [ 51  55  63]
  ..., 
  [ 78 101  99]
  [ 76 102  99]
  [ 76 102  99]]

 ..., 
 [[ 32  35  31]
  [ 31  34  30]


[[[36 46 57]
  [36 46 57]
  [35 45 54]
  ..., 
  [68 87 90]
  [69 90 93]
  [67 88 91]]

 [[39 49 60]
  [38 48 59]
  [34 46 55]
  ..., 
  [67 87 93]
  [69 89 95]
  [68 88 94]]

 [[38 50 61]
  [39 51 62]
  [36 49 56]
  ..., 
  [68 87 95]
  [69 89 95]
  [69 89 95]]

 ..., 
 [[19 27 30]
  [17 25 28]
  [14 18 26]
  ..., 
  [80 57 32]
  [86 58 34]
  [85 57 33]]

 [[18 25 30]
  [17 24 29]
  [14 18 26]
  ..., 
  [80 57 32]
  [83 58 33]
  [84 59 34]]

 [[17 24 29]
  [17 24 29]
  [17 21 29]
  ..., 
  [78 58 30]
  [81 59 31]
  [83 61 33]]]
[[[ 35  47  51]
  [ 34  46  50]
  [ 29  48  45]
  ..., 
  [ 78  83 100]
  [ 77  87 103]
  [ 76  86 102]]

 [[ 35  46  53]
  [ 33  44  51]
  [ 31  45  44]
  ..., 
  [ 75  84  98]
  [ 73  84  98]
  [ 73  84  98]]

 [[ 35  45  54]
  [ 33  43  52]
  [ 32  44  48]
  ..., 
  [ 75  84  98]
  [ 72  83  97]
  [ 72  83  97]]

 ..., 
 [[ 21  29  32]
  [ 21  29  32]
  [ 23  29  32]
  ..., 
  [ 79  56  38]
  [ 81  59  36]
  [ 83  61  38]]

 [[ 19  26  31]
  [ 21  28  33]
  

[[[46 51 56]
  [45 50 55]
  [45 50 55]
  ..., 
  [75 85 94]
  [76 86 95]
  [76 86 95]]

 [[42 49 49]
  [42 49 49]
  [44 51 51]
  ..., 
  [72 85 92]
  [76 87 94]
  [75 86 93]]

 [[42 49 48]
  [42 49 48]
  [44 51 51]
  ..., 
  [69 83 87]
  [74 86 90]
  [74 86 90]]

 ..., 
 [[25 30 26]
  [25 30 26]
  [25 29 28]
  ..., 
  [88 64 36]
  [89 65 37]
  [88 64 36]]

 [[25 27 26]
  [27 29 28]
  [25 29 28]
  ..., 
  [87 63 35]
  [87 63 35]
  [85 61 33]]

 [[25 27 26]
  [25 27 26]
  [25 27 26]
  ..., 
  [84 60 32]
  [83 59 31]
  [83 59 31]]]
[[[45 52 51]
  [45 52 51]
  [44 51 51]
  ..., 
  [77 86 91]
  [74 84 95]
  [72 82 93]]

 [[45 52 51]
  [44 51 50]
  [44 51 50]
  ..., 
  [74 88 87]
  [74 86 95]
  [73 85 94]]

 [[42 49 47]
  [44 51 49]
  [44 51 49]
  ..., 
  [74 88 87]
  [73 87 91]
  [73 87 91]]

 ..., 
 [[25 29 29]
  [22 26 26]
  [22 26 26]
  ..., 
  [84 60 32]
  [83 61 26]
  [82 60 25]]

 [[25 29 29]
  [25 29 29]
  [23 27 27]
  ..., 
  [82 60 32]
  [81 61 26]
  [80 60 25]]

 [[23 30 30]
  [23

[[[ 33  47  51]
  [ 33  47  51]
  [ 30  48  49]
  ..., 
  [ 65  86  98]
  [ 71  84  99]
  [ 71  84  99]]

 [[ 33  46  53]
  [ 34  47  54]
  [ 33  48  50]
  ..., 
  [ 66  85  95]
  [ 71  85  98]
  [ 72  86  99]]

 [[ 36  46  55]
  [ 35  45  54]
  [ 33  47  51]
  ..., 
  [ 68  87  97]
  [ 71  87 100]
  [ 71  87 100]]

 ..., 
 [[ 24  31  31]
  [ 24  31  31]
  [ 24  31  31]
  ..., 
  [ 81  55  44]
  [ 81  58  38]
  [ 83  60  40]]

 [[ 22  31  31]
  [ 22  31  31]
  [ 22  31  31]
  ..., 
  [ 81  56  43]
  [ 81  59  36]
  [ 81  59  36]]

 [[ 20  31  31]
  [ 21  32  32]
  [ 21  32  32]
  ..., 
  [ 83  58  45]
  [ 81  59  36]
  [ 81  59  36]]]
[[[ 23  49  51]
  [ 27  53  55]
  [ 29  53  60]
  ..., 
  [ 65  79  97]
  [ 68  79 101]
  [ 72  83 105]]

 [[ 28  49  52]
  [ 30  51  54]
  [ 32  52  58]
  ..., 
  [ 63  79  97]
  [ 68  81 101]
  [ 70  83 103]]

 [[ 30  49  52]
  [ 33  52  55]
  [ 34  52  58]
  ..., 
  [ 66  82 100]
  [ 69  82 102]
  [ 69  82 102]]

 ..., 
 [[ 24  30  33]
  [ 20  26  29]


[[[35 46 46]
  [36 47 47]
  [38 47 47]
  ..., 
  [34 41 73]
  [36 45 72]
  [36 45 72]]

 [[32 41 40]
  [37 46 45]
  [41 48 46]
  ..., 
  [36 43 75]
  [36 44 74]
  [37 45 75]]

 [[36 45 44]
  [37 46 45]
  [39 48 46]
  ..., 
  [36 43 75]
  [34 43 75]
  [35 44 76]]

 ..., 
 [[19 22 26]
  [19 22 26]
  [16 19 23]
  ..., 
  [62 61 85]
  [65 64 88]
  [67 66 90]]

 [[17 23 26]
  [17 23 26]
  [13 19 22]
  ..., 
  [67 63 88]
  [65 64 88]
  [65 64 88]]

 [[17 23 26]
  [17 23 26]
  [14 20 23]
  ..., 
  [67 63 88]
  [66 65 89]
  [63 62 86]]]
[[[ 32  42  37]
  [ 33  43  38]
  [ 30  41  41]
  ..., 
  [ 26  33  43]
  [ 26  34  42]
  [ 26  34  42]]

 [[ 31  44  37]
  [ 33  46  39]
  [ 33  44  42]
  ..., 
  [ 26  35  49]
  [ 25  35  46]
  [ 24  34  45]]

 [[ 34  48  38]
  [ 37  51  41]
  [ 36  49  42]
  ..., 
  [ 26  34  50]
  [ 25  35  46]
  [ 25  35  46]]

 ..., 
 [[ 79  83 103]
  [ 92  96 116]
  [ 95 101 116]
  ..., 
  [ 63  61  88]
  [ 61  62  86]
  [ 63  64  88]]

 [[ 84  90 111]
  [ 90  96 117]
  

[[[ 19  23  22]
  [ 18  22  21]
  [ 16  25  18]
  ..., 
  [100 113  80]
  [ 91 112  81]
  [ 90 111  80]]

 [[ 16  23  21]
  [ 16  23  21]
  [ 17  25  20]
  ..., 
  [101 113  78]
  [ 94 112  78]
  [ 92 110  76]]

 [[ 16  23  21]
  [ 16  23  21]
  [ 17  26  19]
  ..., 
  [101 114  76]
  [ 94 110  75]
  [ 93 109  74]]

 ..., 
 [[178 180 169]
  [178 180 169]
  [177 179 168]
  ..., 
  [164 165 117]
  [171 167 125]
  [146 142 100]]

 [[175 177 166]
  [176 178 167]
  [176 178 167]
  ..., 
  [153 153 108]
  [154 152 112]
  [143 141 101]]

 [[173 175 162]
  [174 176 163]
  [175 177 164]
  ..., 
  [151 150 114]
  [154 151 115]
  [140 137 101]]]
[[[ 15  21  15]
  [ 18  24  18]
  [ 18  24  13]
  ..., 
  [ 98 110  80]
  [ 99 109  74]
  [ 98 108  73]]

 [[ 15  22  13]
  [ 16  23  14]
  [ 18  24  13]
  ..., 
  [ 98 111  78]
  [ 98 109  76]
  [ 97 108  75]]

 [[ 18  26  15]
  [ 19  27  16]
  [ 18  24  11]
  ..., 
  [ 98 111  78]
  [ 98 109  76]
  [ 98 109  76]]

 ..., 
 [[174 178 167]
  [173 177 166]


[[[ 25  35  46]
  [ 24  34  45]
  [ 24  32  40]
  ..., 
  [ 56  73  83]
  [ 58  74  87]
  [ 57  73  86]]

 [[ 25  35  44]
  [ 24  34  43]
  [ 26  34  42]
  ..., 
  [ 57  76  86]
  [ 57  75  88]
  [ 57  75  88]]

 [[ 25  35  44]
  [ 25  35  44]
  [ 27  35  43]
  ..., 
  [ 60  78  91]
  [ 60  78  91]
  [ 57  75  88]]

 ..., 
 [[111 115 130]
  [101 105 120]
  [100 109 123]
  ..., 
  [195 207 184]
  [191 206 182]
  [190 205 181]]

 [[106 111 128]
  [105 110 127]
  [103 111 127]
  ..., 
  [202 210 185]
  [200 212 187]
  [197 209 184]]

 [[105 113 129]
  [107 115 131]
  [109 117 133]
  ..., 
  [208 212 187]
  [201 211 186]
  [199 209 184]]]
[[[ 21  38  46]
  [ 20  37  45]
  [ 20  37  45]
  ..., 
  [ 53  70  94]
  [ 53  70  94]
  [ 53  70  94]]

 [[ 22  37  45]
  [ 20  35  43]
  [ 19  36  44]
  ..., 
  [ 57  72  94]
  [ 55  70  92]
  [ 55  70  92]]

 [[ 21  36  44]
  [ 21  36  44]
  [ 22  37  45]
  ..., 
  [ 57  72  94]
  [ 56  71  93]
  [ 56  71  93]]

 ..., 
 [[ 99 101 134]
  [ 99 101 134]


[[[ 24  31  43]
  [ 27  34  46]
  [ 27  35  43]
  ..., 
  [ 57  73  91]
  [ 59  72  92]
  [ 59  72  92]]

 [[ 26  33  45]
  [ 27  34  46]
  [ 28  35  45]
  ..., 
  [ 60  76  94]
  [ 64  76  94]
  [ 64  76  94]]

 [[ 28  38  47]
  [ 26  36  45]
  [ 26  36  45]
  ..., 
  [ 60  76  94]
  [ 64  76  94]
  [ 64  76  94]]

 ..., 
 [[150 151 173]
  [147 148 170]
  [146 147 169]
  ..., 
  [204 209 181]
  [200 206 176]
  [199 205 175]]

 [[151 151 178]
  [146 146 173]
  [146 147 171]
  ..., 
  [210 212 185]
  [207 209 182]
  [202 204 177]]

 [[149 152 176]
  [147 150 174]
  [147 148 172]
  ..., 
  [213 215 188]
  [212 216 193]
  [205 209 186]]]
[[[ 28  37  42]
  [ 29  38  43]
  [ 29  37  45]
  ..., 
  [ 54  73  90]
  [ 55  74  91]
  [ 55  74  91]]

 [[ 29  38  43]
  [ 29  38  43]
  [ 29  37  45]
  ..., 
  [ 55  76  88]
  [ 55  76  88]
  [ 55  76  88]]

 [[ 27  38  45]
  [ 27  38  45]
  [ 27  37  46]
  ..., 
  [ 57  75  88]
  [ 57  75  88]
  [ 57  75  88]]

 ..., 
 [[151 154 178]
  [154 157 181]


[[[ 21  32  31]
  [ 21  32  31]
  [ 22  33  33]
  ..., 
  [ 44  64  78]
  [ 49  64  79]
  [ 50  65  80]]

 [[ 21  32  32]
  [ 22  33  33]
  [ 23  33  36]
  ..., 
  [ 44  64  78]
  [ 48  65  80]
  [ 48  65  80]]

 [[ 22  32  35]
  [ 23  33  36]
  [ 23  33  36]
  ..., 
  [ 46  63  78]
  [ 50  65  80]
  [ 51  66  81]]

 ..., 
 [[104 107 129]
  [102 105 127]
  [103 105 120]
  ..., 
  [183 191 173]
  [185 192 176]
  [179 186 170]]

 [[106 112 135]
  [105 111 134]
  [109 112 134]
  ..., 
  [183 192 171]
  [184 192 174]
  [183 191 173]]

 [[107 113 136]
  [107 113 136]
  [109 115 138]
  ..., 
  [185 193 170]
  [184 192 174]
  [185 193 175]]]
[[[ 20  34  33]
  [ 21  35  34]
  [ 21  35  34]
  ..., 
  [ 48  63  78]
  [ 48  61  83]
  [ 47  60  82]]

 [[ 22  33  33]
  [ 23  34  34]
  [ 21  34  36]
  ..., 
  [ 50  66  79]
  [ 49  63  81]
  [ 48  62  80]]

 [[ 20  33  35]
  [ 21  34  36]
  [ 21  33  37]
  ..., 
  [ 51  67  80]
  [ 49  63  81]
  [ 49  63  81]]

 ..., 
 [[109 108 130]
  [105 104 126]


[[[ 20  31  45]
  [ 19  30  44]
  [ 19  30  44]
  ..., 
  [ 49  59  84]
  [ 51  64  79]
  [ 51  64  79]]

 [[ 20  31  45]
  [ 19  30  44]
  [ 19  30  44]
  ..., 
  [ 52  62  87]
  [ 50  62  80]
  [ 51  63  81]]

 [[ 19  31  42]
  [ 19  31  42]
  [ 18  30  41]
  ..., 
  [ 51  62  84]
  [ 48  60  78]
  [ 49  61  79]]

 ..., 
 [[163 131 167]
  [156 124 160]
  [147 113 156]
  ..., 
  [189 194 178]
  [188 191 182]
  [183 186 177]]

 [[164 134 165]
  [158 128 159]
  [150 117 155]
  ..., 
  [193 195 177]
  [187 189 178]
  [184 186 175]]

 [[162 136 160]
  [159 133 157]
  [162 132 163]
  ..., 
  [196 199 178]
  [192 195 179]
  [192 195 179]]]
[[[ 23  33  36]
  [ 22  32  35]
  [ 21  30  35]
  ..., 
  [ 47  67  73]
  [ 45  63  76]
  [ 44  62  75]]

 [[ 23  33  36]
  [ 22  32  35]
  [ 22  32  35]
  ..., 
  [ 47  66  74]
  [ 46  64  77]
  [ 46  64  77]]

 [[ 22  35  37]
  [ 21  34  36]
  [ 23  33  36]
  ..., 
  [ 48  67  77]
  [ 48  66  79]
  [ 46  64  77]]

 ..., 
 [[151 119 155]
  [156 124 160]


[[[ 18  34  40]
  [ 20  36  42]
  [ 20  36  42]
  ..., 
  [ 48  65  75]
  [ 50  66  79]
  [ 50  66  79]]

 [[ 18  34  40]
  [ 18  34  40]
  [ 18  34  40]
  ..., 
  [ 47  65  78]
  [ 50  66  79]
  [ 49  65  78]]

 [[ 18  34  40]
  [ 17  33  39]
  [ 17  33  39]
  ..., 
  [ 48  66  79]
  [ 49  65  78]
  [ 49  65  78]]

 ..., 
 [[160 127 165]
  [161 128 166]
  [162 128 171]
  ..., 
  [187 189 178]
  [187 191 180]
  [186 190 179]]

 [[163 133 169]
  [163 133 169]
  [162 129 167]
  ..., 
  [188 192 179]
  [190 193 184]
  [185 188 179]]

 [[169 139 170]
  [165 135 166]
  [162 131 164]
  ..., 
  [192 197 181]
  [192 196 185]
  [190 194 183]]]
[[[ 21  33  37]
  [ 20  32  36]
  [ 15  32  35]
  ..., 
  [ 39  66  79]
  [ 41  67  78]
  [ 41  67  78]]

 [[ 19  34  36]
  [ 18  33  35]
  [ 16  34  35]
  ..., 
  [ 39  64  77]
  [ 42  63  80]
  [ 43  64  81]]

 [[ 17  36  34]
  [ 16  35  33]
  [ 14  34  35]
  ..., 
  [ 41  62  79]
  [ 43  64  81]
  [ 43  64  81]]

 ..., 
 [[138 141 163]
  [138 141 163]


[[[ 35  47  65]
  [ 35  47  65]
  [ 36  47  67]
  ..., 
  [ 79  99 113]
  [ 74  98 114]
  [ 72  96 112]]

 [[ 32  46  64]
  [ 33  47  65]
  [ 34  48  66]
  ..., 
  [ 81 102 114]
  [ 78  98 112]
  [ 78  98 112]]

 [[ 30  46  59]
  [ 34  50  63]
  [ 35  50  65]
  ..., 
  [ 80 102 111]
  [ 79 100 112]
  [ 78  99 111]]

 ..., 
 [[ 25  29  37]
  [ 24  28  36]
  [ 26  27  36]
  ..., 
  [232 235 206]
  [230 234 209]
  [232 236 211]]

 [[ 24  29  34]
  [ 21  26  31]
  [ 21  25  33]
  ..., 
  [238 239 210]
  [235 236 214]
  [232 233 211]]

 [[ 28  31  35]
  [ 26  29  33]
  [ 25  27  33]
  ..., 
  [240 241 212]
  [236 237 215]
  [235 236 214]]]
[[[ 34  55  52]
  [ 33  54  51]
  [ 30  51  49]
  ..., 
  [ 83  94 108]
  [ 78  96 109]
  [ 78  96 109]]

 [[ 32  53  51]
  [ 33  54  52]
  [ 33  54  52]
  ..., 
  [ 83  94 108]
  [ 79  96 106]
  [ 80  97 107]]

 [[ 35  52  55]
  [ 35  52  55]
  [ 32  52  53]
  ..., 
  [ 82  93 107]
  [ 85 100 110]
  [ 86 101 111]]

 ..., 
 [[ 30  31  35]
  [ 29  30  34]


[[[ 48  69  67]
  [ 50  71  69]
  [ 49  75  70]
  ..., 
  [ 91 110  99]
  [ 96 115 104]
  [ 95 114 103]]

 [[ 47  68  66]
  [ 48  69  67]
  [ 45  68  65]
  ..., 
  [ 94 111 105]
  [ 97 115 107]
  [ 93 111 103]]

 [[ 47  68  66]
  [ 48  69  67]
  [ 45  68  65]
  ..., 
  [ 95 112 106]
  [ 98 116 108]
  [ 95 113 105]]

 ..., 
 [[ 34  39  30]
  [ 34  39  30]
  [ 35  39  33]
  ..., 
  [250 255 211]
  [246 253 212]
  [244 251 210]]

 [[ 35  40  31]
  [ 36  41  32]
  [ 37  41  35]
  ..., 
  [249 255 215]
  [246 253 212]
  [246 253 212]]

 [[ 33  40  31]
  [ 33  40  31]
  [ 32  38  32]
  ..., 
  [249 255 215]
  [249 255 215]
  [246 253 212]]]
[[[ 48  66  67]
  [ 44  62  63]
  [ 45  60  62]
  ..., 
  [ 99 122 108]
  [ 91 114 100]
  [ 92 115 101]]

 [[ 50  68  69]
  [ 49  67  68]
  [ 44  63  60]
  ..., 
  [ 94 117 103]
  [ 90 110  97]
  [ 97 117 104]]

 [[ 50  69  66]
  [ 48  67  64]
  [ 42  61  58]
  ..., 
  [ 91 114 100]
  [ 94 114 101]
  [ 96 116 103]]

 ..., 
 [[ 31  38  37]
  [ 32  39  38]


[[[ 46  71  57]
  [ 41  66  52]
  [ 42  66  47]
  ..., 
  [ 97 112 106]
  [ 92 111 107]
  [ 91 110 106]]

 [[ 48  68  61]
  [ 45  65  58]
  [ 43  65  53]
  ..., 
  [ 93 112 108]
  [ 91 110 106]
  [ 92 111 107]]

 [[ 51  67  65]
  [ 48  64  62]
  [ 48  63  57]
  ..., 
  [ 95 114 110]
  [ 94 113 109]
  [ 93 112 108]]

 ..., 
 [[ 35  40  36]
  [ 32  37  33]
  [ 29  34  30]
  ..., 
  [237 244 184]
  [246 253 200]
  [250 255 204]]

 [[ 34  39  35]
  [ 34  39  35]
  [ 32  37  33]
  ..., 
  [248 254 197]
  [250 255 204]
  [248 255 202]]

 [[ 34  37  33]
  [ 35  38  34]
  [ 32  37  33]
  ..., 
  [250 255 205]
  [253 255 208]
  [246 252 201]]]
[[[ 52  64  59]
  [ 54  66  61]
  [ 52  69  63]
  ..., 
  [ 85 111  99]
  [ 87 114 100]
  [ 88 115 101]]

 [[ 56  68  63]
  [ 57  69  64]
  [ 50  67  61]
  ..., 
  [ 88 113 104]
  [ 89 115 103]
  [ 87 113 101]]

 [[ 56  68  63]
  [ 59  71  66]
  [ 52  69  63]
  ..., 
  [ 87 113 101]
  [ 89 115 103]
  [ 87 113 101]]

 ..., 
 [[ 34  41  39]
  [ 34  41  39]


[[[ 36  51  61]
  [ 35  50  60]
  [ 38  52  56]
  ..., 
  [ 68  99  94]
  [ 68  99  94]
  [ 69 100  95]]

 [[ 41  52  59]
  [ 39  50  57]
  [ 38  46  54]
  ..., 
  [ 67  98  93]
  [ 67  98  93]
  [ 67  98  93]]

 [[ 41  52  59]
  [ 38  49  56]
  [ 35  43  51]
  ..., 
  [ 65  98  93]
  [ 65  98  93]
  [ 65  98  93]]

 ..., 
 [[ 27  30  34]
  [ 27  30  34]
  [ 26  31  36]
  ..., 
  [230 236 199]
  [227 232 198]
  [227 232 198]]

 [[ 27  30  34]
  [ 28  31  35]
  [ 26  32  35]
  ..., 
  [225 231 192]
  [227 233 196]
  [228 234 197]]

 [[ 25  31  34]
  [ 26  32  35]
  [ 26  32  35]
  ..., 
  [230 237 196]
  [229 235 198]
  [230 236 199]]]
[[[ 27  46  42]
  [ 24  43  39]
  [ 24  44  37]
  ..., 
  [ 71  87  93]
  [ 77  92  94]
  [ 76  91  93]]

 [[ 27  46  42]
  [ 25  44  40]
  [ 28  42  39]
  ..., 
  [ 71  88  91]
  [ 71  89  90]
  [ 77  95  96]]

 [[ 29  45  42]
  [ 27  43  40]
  [ 28  42  39]
  ..., 
  [ 69  88  91]
  [ 69  88  91]
  [ 73  92  95]]

 ..., 
 [[ 23  27  28]
  [ 25  29  30]


KeyboardInterrupt: 